### ISSUE TITLE
Oculus Quest support

### ISSUE THREAD

**Issue by kripper** [etlegacy/etlegacy-android#1]
Any chance to support Oculus Quest?
Please also see: https://github.com/DrBeef/RTCWQuest

**Comment by rafal1137** [comment]
I do not own Oculus at all. So there is no way for me to test thing.

**Comment by isRyven** [comment]
I see it as a feature request ticket, hence someone else could always pick this up and start working on it, using this ticket to track the progress, i don't personally see any point in closing this. Could instead put some help wanted label on it, and let it exist?

**Comment by rafal1137** [comment]
> Could instead put some help wanted label on it, and let it exist?

If there will be someone with time and device at his hand why not.

**Comment by kripper** [comment]
You should own one and play onward :-)

**Comment by kripper** [comment]
Single Player mod has been released for RTCWQuest:
https://www.moddb.com/downloads/etsp

**Comment by kripper** [comment]
Nevermind, Pavlov's already has custom maps like D-Day in push mode and also custom maps imported from the original Enemy Territory maps.
We should better go with Pavlov.
