### ISSUE TITLE
Update submodule automatically

### ISSUE THREAD

**Issue by rmarquis** [etlegacy/etlegacy-android#2]
I haven't tried, but to make your life easier you might want to have a look at updating the submodule through Github action:
https://stackoverflow.com/questions/64407333/using-github-actions-to-automatically-update-the-repos-submodules

Basically a new step that would run as a before android compilation in the global ETLBuild.

**Comment by rafal1137** [comment]
Applied in: https://github.com/etlegacy/etlegacy/commit/33ca1bc1480ac3e883ea4f6280aa83d2296e0eb4

**Comment by rmarquis** [comment]
Looks like it works!

**Comment by rafal1137** [comment]
Yes it does. Closing
